ChooseHouse
WildCodeSchool-2024-09/JS-RemoteFR-Vendangeurs-P2-HAPI-Router pull request #1
Opened 2024-11-15 08:59 UTC by Pene891

2024-11-15 09:25 UTC, JeremyPerezGit approved these changes

2024-11-15 10:29 UTC, Vincent-Ching approved these changes

2024-11-15 11:37 UTC, ioayoub approved these changes

2024-11-18 14:12 UTC, rocambille requested changes, later dismissed

2024-11-18 14:12 UTC, rocambille commented on client/src/ChooseHouseHome.tsx
> +        </div>
à mettre dans un composant Card

2024-11-18 14:12 UTC, rocambille commented on client/src/ChooseHouseHome.tsx
> +        </div>
à remplacer par un appel du composant Card ;)

2024-11-21 10:11 UTC, Brian-boudrioux approved these changes

2024-11-21 10:16 UTC, merged