Up design
WildCodeSchool-2024-09/JS-RemoteFR-Vendangeurs-P2-HAPI-Router pull request #16
Opened 2024-11-25 19:12 UTC by Pene891

Modification de l'accueil avec un aspect plus design

2024-11-26 14:02 UTC, Vincent-Ching approved these changes

2024-11-26 14:05 UTC, JeremyPerezGit approved these changes

2024-11-26 16:17 UTC, Brian-boudrioux requested changes
conflits à gérer avant de pouvoir valider

2024-11-26 16:32 UTC, Brian-boudrioux approved these changes

2024-11-27 08:48 UTC, Vincent-Ching approved these changes

2024-11-27 09:02 UTC, merged